apiVersion: batch/v1
kind: Job
metadata:
  name: job-name-placeholder
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: esm-inference
        image: "us-west1-docker.pkg.dev/hsu-matthewnemeth-personal/esm-docker/esm@sha256:ae72c25938ac4fc9825e31f7548adc42f402c83f9144b98fdeba036b449776d5"
        resources:
          limits:
            nvidia.com/gpu: 1
          requests:
            cpu: "6"
            memory: "30Gi"
            ephemeral-storage: "15Gi"

        command: ["python3", "esmfold.py", "bucket-name-placeholder"]
        # command: ["sleep", "infinity"]
      nodeSelector:
        cloud.google.com/gke-nodepool: esm-inference-pool
        cloud.google.com/gke-accelerator: "nvidia-tesla-t4"
        iam.gke.io/gke-metadata-server-enabled: "true"
      restartPolicy: OnFailure
      serviceAccountName: esm-job